export const wordMap = {
  "hello": "zhorp",
  "bye": "aglorf",
  "yes": "yorg",
  "alien": "lalus",
  "human": "gleeple",
  "person": "thirgla",
  "bitch": "yham",
  "chicken": "gongle",
  "big": "ungys",
  "small": "thierg",
  "fuck": "pbogle",
  "very": "hounzi",
  "alien lang": "lalusius",
  "language": "tarthrop",
  "alien planet": "thungus",
  "this": "bvo",
  "butt": "zhlep",
  "cool": "zeebe",
  "and": "ag",
  "wrong": "gloz",
  "hop": "klorn",
  "general": "mingus",
  "english": "bleebla",
  "boob": "zhazhla",
  "mod": "ploh",
  "lounge": "krlahp",
  "voice": "cloku",
  "server": "ghyalm",
  "text": "glahb",
  "an": "o",
  "a": "o",
  "important": "lokvhor",
  "rule": "zanrok",
  "channel": "qlok",
  "stupid": "glorplak",
  "food": "hlagle",
  "water": "korgla",
  "bbc": "bibcunbo",
  "big black cock": "bibcunbo",
  "of": "yak",
  "negative action": "gnarp",
  "only": "fnom",
  "woman": "xiyakzhla",
  "significant": "zeergon",
  "silence": "quorgle",
  "guide": "lahmkrap",
  "better": "flarza",
  "official": "ryqriaog",
  "translate": "brimfon",
  "ok": "blavb",
  "okay": "blavb",
  "don't": "Vlorg",
  "dont": "Vlorg",
  "something": "zoemah",
  "faggot": "nungus",
  "lgas": "zunger", //light green alien slur
  "by": "glis",
  "god": "glius",
  "Nice": "dyrpa",
  "lgar": "zonge", //light green alien race
  "dgar": "gauvha", //dark green alien race
  "guy": "zinp",
  "race": "omzqing",
  "dollar": "lapung", //Alien Currency
  "also": "lul",
  "name": "lungl",
  "to": "ak",
  "too": "ak",
  "money": "pung", //Currancy
  "please": "Kohndya",
  "so": "orvk",
  "time": "qunsp",
  "will": "ung ",
  "trial": "yarkfla",
  "stfu": "bongigloo",
  "results": "ryunfa",
  "about": "dnpo",
  "with": "puagla",
  "stinky": "maugi",
  "penis": "gloub",
  "maybe": "shlinga",
  "leak": "klofle",
  "information": "triushga",
  "request": "fliflouf",
  "!": "~",
  "?": ";",
  "the": "glo",
  "it": "ix",
  "her": "zha",
  "she": "zha",
  "you": "qu",
  "i": "uw",
  "my": "ow",
  "our": "mog",
  "they": "glerba",
  "we": "glerbo",
  "he": "zho",
  "him": "zho",
  "who": "havla",
  "what": "hovl",
  "where": "xezha",
  "why": "glorple",
  "how": "slarg",
  "hi": "zhorp",
  "hello": "zhorp",
  "bye": "aglorf",
  "gay": "gay",
  "all": "plaqa",
 
  ///////VERBS//////

  "is": "moz",
  "are": "moz",
  "am": "moz",
  "walk": "klav",
  "feel": "zuhit",
  "run": "brazh",
  "hit": "wuexha",
  "use": "lersp",
  "want": "zeerbger",
  "know": "glubin",
  "be": "ju",
  "have": "xix",
  "must": "laigle",
  "should": "laigle",
  "look": "pofl",
  "look": "pofl",
  "like": "kag",
  "love": "klag",
  "ask": "tevle",
  "cap": "agluz",
  "do": "uhk",
  "verify": "drigklahn",
  "come": "tyntla",
  "join": "xlamb",
  "cum": "auagugh",
  "write": "plarb",
  "make": "taruk",
  "mean": "nakx",
  "speak": "glavp",
  "think": "derzha",
  "believe": "derzha",
  "learn": "vuaxle",
  "keep": "zahr",
  "prove": "lakyah",
  "send": "trayhn",
  "pass": "nyrak",
  "tell": "mhakvo",
  "can": "flabla",
  "require": "doglor",
  "eat": "sorvlog",
  "lie": "quable",
  "ban": "plakla",
  "rape": "pbiblar",
  "": "",
  
  // Add more word mappings as needed
};
